version: "3.3"

services:
  redis_server:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbit_mq_server:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - LISTEN_ADDR=:8080
      - REDIS_HOST=redis_server:6379
      - REPOSITORY=DISTRIBUTED
      - AMQP_URL=amqp://rabbit_mq_server
    depends_on:
      - rabbit_mq_server
      - redis_server

  stats_consumer:
    build:
      context: ..
      dockerfile: deployments/stats.Dockerfile
    env_file:
      - ../.env
    restart: unless-stopped
    environment:
      - LISTEN_ADDR=:8080
      - REDIS_HOST=redis_server:6379
      - REPOSITORY=MYSQL
      - AMQP_URL=amqp://rabbit_mq_server
    depends_on:
      - rabbit_mq_server