version: "3.3"

services:
  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      - LISTEN_ADDR=:8080
      - REPOSITORY=MYSQL